### PR TITLE
Correct parsing for action type='delete'

### LINKED ISSUE #11: Every change type should have a "new"
The XML from Overpass's augmented diffs will always have a `<new>` section (except in `<action type="create">`), so it should always be parsed that way.

For example, this chunk of XML from a recent augmented diff did not have a `neu` attribute:

``` xml
<action type="delete">
<old>
  <way id="392501147" version="1" timestamp="2016-01-20T19:44:40Z" changeset="36708221" uid="77947" user="Roman Guy">
    <bounds minlat="50.6588902" minlon="4.1665570" maxlat="50.6595783" maxlon="4.1670295"/>
    <nd ref="332420418" lat="50.6595783" lon="4.1665570"/>
    <nd ref="3957185029" lat="50.6592359" lon="4.1667953"/>
    <nd ref="2190187178" lat="50.6592061" lon="4.1668160"/>
    <nd ref="3957185032" lat="50.6591835" lon="4.1668312"/>
    <nd ref="3957185014" lat="50.6588902" lon="4.1670295"/>
    <tag k="highway" v="footway"/>
  </way>
</old>
<new>
  <way id="392501147" visible="false" version="2" timestamp="2016-01-20T20:24:37Z" changeset="36708913" uid="77947" user="Roman Guy"/>
</new>
</action>
```

### PR DESCRIPTION
**Pull request by iandees**
Fixes #11.

See docs for augmented diffs here: http://wiki.openstreetmap.org/wiki/Overpass_API/Augmented_Diffs

### CODE REVIEW

**Comment by iandees** [comment]
I didn't merge this myself because I don't think I have access to post to npm. @morganherlocker or @tmcw, do you?

**Comment by tmcw** [comment]
@ian29 i added you to the owners of the package, you should be able to push now.

**Comment by iandees** [comment]
Thanks @tmcw.

**Comment by ian29** [comment]
:wave: @iandees

**Pull request merged**
